config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :outfits do
    resources :shoes, only: [:new, :create, :edit, :update]
    resources :feedbacks, only: [:create, :update]
  end

  resources :shoes, only: [:destroy] do
    # like method in shoes controller
    member do
      put "like" => "shoes#like"
    end
    resources :wishes, only: :create
  end

  resources :feedbacks, only: [:destroy]
  resources :users, only: [:show]

  get "trending", to: "outfits#trending"
end

app/models/outfit.rb
class Outfit < ApplicationRecord
include ActionView::Helpers::TextHelper
  EVENT_TYPES = %w[wedding_or_bridal business cocktail_party ball_or_prom party night_out formal_event casual_event a_date outdoor_event]
  WALKING_TIME = %w[under_1_hr up_to_5_hrs more_than_5_hrs]
  belongs_to :user
  has_many :shoes, dependent: :destroy
  has_many :feedbacks
  has_many :outfit_categories, dependent: :destroy
  has_many :categories, through: :outfit_categories
  has_one_attached :photo
  self.per_page = 6


  def event_type_icon
    if event_type == "date" || event_type == "a_date"
      return "far fa-kiss-wink-heart"
    elsif event_type == "wedding_or_bridal"
      return "fas fa-dove"
    elsif event_type == "business"
      return "fas fa-briefcase"
    elsif event_type == "cocktail_party"
      return "fas fa-cocktail"
    elsif event_type == "ball_or_prom"
      return "fas fa-music"
    elsif event_type == "party"
      return "fas fa-birthday-cake"
    elsif event_type == "night_out"
      return "fas fa-glass-cheers"
    elsif event_type == "formal_event"
      return "fas fa-user-tie"
    elsif event_type == "casual_event"
      return "fas fa-tshirt"
    elsif event_type == "outdoor_event"
      return "fas fa-tree"
    end
  end

  def walking_time_icon
    if walking_time == "under_1_hr" || walking_time == "under_one_hour"
      return "fas fa-walking"
    elsif walking_time == "up_to_5_hrs" || walking_time == "up_to_5_hours"
      return "fas fa-running"
    elsif walking_time == "more_than_5_hrs" || walking_time == "more_than_5_hours"
      return "fas fa-hiking"
    end
  end
  
  def time_left
    hours = ((event_date - Time.now)/3600).round
    if hours < 24
      return pluralize(hours, 'hour')
    else
      return pluralize(hours/24, 'day')
    end
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index
  def index
    @outfits = Outfit.includes([:shoes, :user, :photo_attachment]).order(created_at: :desc).paginate(page: params[:page]) # checked!
    @new_outfit = Outfit.new
    @user = current_user
    @feedback = Feedback.new
  end

  def show
    @shoe = Shoe.new
    @shoes = @outfit.shoes
    @new_outfit = Outfit.new()
    if @shoes
      shoe_ids = @shoes.map(&:id)
      category_names = @shoes.map(&:categories).flatten.map(&:name).uniq
      @recommended_shoe = Shoe.joins(:categories).where.not(id: shoe_ids).where('categories.name in (?)', category_names).where.not(url: [nil, '']).sort_by { |shoe| -(shoe.categories.map(&:name) - category_names).size }.first
    end
  end

  def new
    @outfit = Outfit.new
  end

  def create
    @outfit = Outfit.new(outfit_params)
    @outfit.user = current_user
    @user = current_user
    if @outfit.save
      flash[:notice] = "Success!"
      redirect_to outfit_path(@outfit)
    else
      flash[:alert] = "Ooops, something went wrong!"
      render :new
    end
  end

  def edit
  end

  def update
    if @outfit.update(outfit_params)
      flash[:notice] = "Success!"
      redirect_to outfit_path(@outfit)
    else
      flash[:alert] = "Ooops, something went wrong!"
      render :edit
    end
  end

  def destroy
    @outfit.destroy
    redirect_to user_path(current_user)
  end

  def trending
    @trending_shoes = Shoe.all.sort_by { |shoe| -shoe.votes_for.size }.first(3)
    @new_outfit = Outfit.new
  end

  private

  def set_outfit
    @outfit = Outfit.find(params[:id])
  end

  def outfit_params
    params.require(:outfit).permit(:photo, :brand, :event_type, :event_date, :walking_time, category_ids: [])
  end
end

app/views/outfits/_edit_form.html.erb
<%= simple_form_for(outfit) do |f| %>
  <%= f.input :event_type,
              collection: Outfit::EVENT_TYPES,
              as: :select,
              label_method: :humanize %>
  <%= f.input :event_date,
              as: :string,
              required: false,
              input_html: {class: "flattpicker"} %>
  <%= f.input :walking_time,
              collection: Outfit::WALKING_TIME,
              as: :select,
              label_method: :humanize %>
  <%= f.association :categories,
              as: :check_boxes,
              item_wrapper_class: 'category-item',
              input_html: {class: 'category-selector'},
              collection:  Category.where(shoe:false).last(8),
              label:"Outfit Style:",
              label_method: lambda { |category| category.name.humanize} %>
  <%= f.association :categories,
              as: :check_boxes,
              item_wrapper_class: 'category-item',
              input_html: {class: 'category-selector'},
              collection:  Category.where(shoe:false).first(16),
              label:"Main Outfit Colour:",
              label_method: lambda { |category| category.name.humanize} %>
  <%= f.input :photo, input_html: { class: 'hidden', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>

  <% if outfit.new_record? %>
    <%= f.submit "Upload your outfit!", class: "blue-btn" %>
  <% else %>
    <%= f.submit "Edit your outfit!", class: "blue-btn" %>
  <% end %>
<% end %>

app/views/outfits/_form.html.erb
<div class="margin-container">
  <% outfit = Outfit.new if devise_controller? %>
  <%= simple_form_for outfit do |f| %>
    <%= f.input :event_type,
                collection: Outfit::EVENT_TYPES,
                as: :select, label_method: :humanize %>
    <%= f.input :event_date,
                as: :string,
                required: false,
                input_html: {class: "flattpicker"} %>
    <%= f.input :walking_time,
                collection: Outfit::WALKING_TIME,
                as: :select,
                label_method: :humanize %>
    <%= f.association :categories,
                as: :check_boxes,
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector'},
                collection: Category.where(shoe:false).last(8),
                label:"Outfit Style:",
                value_method: :id,
                label_method: lambda { |category| category.name.humanize } %>
    <%= f.association :categories,
                as: :check_boxes,
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector'},
                collection: Category.where(shoe:false).first(16),
                label:"Main Outfit Colour:",
                label_method: lambda { |category| category.name.humanize} %>

    <%= f.input :photo, input_html: { class: 'hidden', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>

    <% if outfit.new_record? %>
      <%= f.submit "Upload your outfit!", class: "blue-btn special" %>
    <% else %>
      <%= f.submit "Edit your outfit!", class: "btn btn-warning" %>
    <% end %>
  <% end %>
</div>

app/views/outfits/_outfit.html.erb
<div class="outfit">
  <div class="outfit-main"></div>
  <div class="shoe-column">
  <% outfit.shoes.each do |shoe| %>
    <div class="shoe"></div>
  <% end %>
  </div>

    
</div>

app/views/outfits/edit.html.erb
<div class="offset-sm-4 col-sm-4">
  <%= render "form", outfit: @outfit %>
</div>

app/views/outfits/index.html.erb
<div class="container pbbig">
    <!-- OUTFIT PART -->
  <% @outfits.each do |outfit| %>
    <div class='outfit-index-card-2 mt-2'>
      <div class="d-flex flex-column">
        <div class="top-bar mb-2">
          <%= image_tag outfit.user.avatar.attached? ? outfit.user.avatar : "photo.png", alt: "alttext", class: 'avatar mr-3' %>
          <div class="user-info">
            <h5><%= link_to "@#{outfit.user.username}", user_path(outfit.user) %></h5>
            <p><%= outfit.user.outfits.length %> outfits completed</p>
          </div>
        </div>
        <div class="d-flex">
          <div class="d-flex flex-column outfit-photo-2">
            <div class="outfit-photo" style="background-image: url('<%= outfit.photo.attached? ? cl_image_path(outfit.photo.key) : 'photo.png' %>');" loading="lazy">
            </div>
            <div class="description_box">
              <% if outfit.event_date && (outfit.event_date - Time.now)/3600 >= 2 %>
                <p><i class="fas fa-history"></i> <%= outfit.time_left %>  left to vote</p>
              <% else %>
                <p>Votes are closed!</p>
              <% end %>
              <p><i class="<%= outfit.event_type_icon %>"></i> <%= outfit.event_type&.humanize  || "has not been set" %></p>
              <p><i class="<%= outfit.walking_time_icon %>"></i> <%= outfit.walking_time&.humanize || "0" %></p>
              <p>
               <a class="" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                  <i class="far fa-comment"></i> <%= outfit.feedbacks.count %> Comments
                </a>
              </p>
              <div class="collapse" id="collapseExample">
                <% if user_signed_in? %>
                  <%= simple_form_for [outfit, @feedback] do |f| %>
                    <%= f.input :content, label: false, class: "container-content" %>
                    <%= f.submit "Add a comment", class: "btn btn-primary" %>
                  <% end %>
                  <% outfit.feedbacks.each do |feedback| %>
                  <p><%= feedback.user.username %>: <%= feedback.content %>
                   <%= link_to feedback_path(feedback), method: :delete, remote: :true do %>
                    <i class="fas fa-minus"></i>
                      <% end %>
                      </p>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="f-col">
            <% outfit.shoes.includes(:photo_attachment).each do |shoe| %>
              <div class="shoe-div" style="background-image: url('<%= shoe.photo.attached? ? cl_image_path(shoe.photo.key) : "" %>')">
                <div class="tl">
                  <span id="shoe-<%= shoe.id %>">
                    <%= shoe.get_likes(vote_scope: outfit.id).count%>
                  </span>
                  <% if user_signed_in? %>
                    <% if current_user.liked? shoe, vote_scope: outfit.id %>
                      <%= link_to like_shoe_path(shoe, "unlike", from: "index", vote_scope: outfit.id), class: 'red-like', method: :put, remote: :true do  %>
                        <i class="fas fa-heart red-like"></i>
                      <% end %>
                      <% elsif ((Time.now - (outfit.event_date || Time.now))/3600  <= -2) %>
                      <%= link_to like_shoe_path(shoe, "like", from: "index", vote_scope: outfit.id), method: :put, remote: :true do  %>
                        <i class="far fa-heart"></i>
                      <% end %>
                    <% else %>
                     <i class="far fa-heart"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            <% end %>
              <% shoes = outfit.shoes.includes([:shoe_categories, :categories]) %>
              <% unless shoes.empty? %>
                <% shoe_ids = shoes.map(&:id)%>
                <% category_names = shoes.map(&:categories).flatten.map(&:name).uniq%>
                <% recommended_shoe = Shoe.joins(:categories).where.not(id: shoe_ids).where('categories.name in (?)', category_names).where.not(url: [nil, '']).sort_by { |shoe| -(shoe.categories.map(&:name) - category_names).size }.first %>
                <% if recommended_shoe.present? && recommended_shoe.photo.attached?%>
                    <div class="shoe-div" style="background-image: url('<%= recommended_shoe.photo.attached? ? cl_image_path(recommended_shoe.photo.key) : "" %>')" loading="lazy">
                      <div class="btn-group dropleft dropdown-options">
                       <i id="dropdown_menue_shoe_<%= recommended_shoe.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                      </div>
                      <div class="tl">
                        <span id="shoe-<%= recommended_shoe.id %>">
                          <%= recommended_shoe.get_likes(vote_scope: outfit.id).count%>
                        </span>
                        <% if user_signed_in? %>
                          <% if current_user.liked? recommended_shoe, vote_scope: outfit.id %>
                            <%= link_to like_shoe_path(recommended_shoe, "unlike", from: "index", vote_scope: outfit.id), class: 'red-like', method: :put, remote: :true do  %>
                              <i class="fas fa-heart"></i>
                            <% end %>
                            <% elsif ((Time.now - (outfit.event_date || Time.now))/3600  <= -2) %>
                            <%= link_to like_shoe_path(recommended_shoe, "like", from: "index", vote_scope: outfit.id), method: :put, remote: :true do  %>
                              <i class="far fa-heart"></i>
                            <% end %>
                          <% else %>
                           <i class="far fa-heart"></i>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= will_paginate @outfits %>
</div>
<% if params[:scroll].present? %>
  <script>
    document.addEventListener('turbolinks:load', () => {
      if (localStorage['scroll']) {
        window.scrollTo({ top: localStorage['scroll'] });
      }
    });
  </script>
<% end %>

<script>
  document.addEventListener('turbolinks:load', () => {
    window.addEventListener('scroll', () => {
      localStorage['scroll'] = window.scrollY;
    });
  })
</script>

app/views/outfits/new.html.erb
<div class="offset-sm-4 col-sm-4">
  <%= render "form", outfit: @outfit, user: current_user %>
</div>

app/views/outfits/show.html.erb
<div class="whole_outfit_container">
  <div class="outfit_header">
    <h2 class="h-showpage">My Outfit</h2>
    <p class="p-showpage">Upload up to 3 Shoe images here</p>
  </div>
  <%# card to display outfit pic %>
  <div class="container d-flex justify-content-between p-2 edit-outfit">
    <div class="outfit-photo" style="background-image: url('<%= @outfit.photo.attached? ? cl_image_path(@outfit.photo.key) : "" %>')">
      <% if current_user == @outfit.user %>
      <div class="btn-group dropleft dropdown-options">
        <i class="fas fa-ellipsis-v" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
        <div class="dropdown-menu">
          <div data-toggle="modal" data-target="#exampleModal">
              <p class='edit-user'>Edit Outfit</p>
          </div>
          <%= link_to "Delete Outfit", outfit_path(@outfit), class:'logout', method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </div>
      <% end %>
    </div>

    <%# card to display shoe pic %>
    <div class="f-col edit-outfit">
      <% @shoes.first(3).each_with_index do |shoe, index| %>
        <div class="shoe-div" style="background-image: url('<%= shoe.photo.attached? ? cl_image_path(shoe.photo.key) : "" %>')">
          <% if current_user == @outfit.user %>
          <div class="btn-group dropleft dropdown-options">
            <i class="fas fa-ellipsis-v" id="dropdown_menue_shoe_<%= shoe.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu" aria-labelledby="dropdown_menue_shoe_<%= shoe.id %>">
              <%= link_to "Edit Shoes", edit_outfit_shoe_path(@outfit, shoe), class: "edit-user mb-2" %>
              <%= link_to "Delete Shoes", shoe_path(shoe), class: "logout", method: :delete, data: { confirm: "Are you sure?" }%>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
      <% length = 3 - @shoes.length %>
      <% if current_user == @outfit.user %>
        <% length.times do  %>
          <div class="add-shoe-div" data-toggle="modal" data-target="#newshoeModal">
            <h1>+</h1>
          </div>
        <% end %>
      <% end %>
      <% unless @shoes.empty? %>
      <% if @recommended_shoe.present? && @recommended_shoe.photo.attached?%>
        <div class="shoe-div reco-shoe" style="background-image: url('<%= @recommended_shoe.photo.attached? ? cl_image_path(@recommended_shoe.photo.key) : "" %>')">
          <div class="btn-group dropleft dropdown-options">
            <i class="fas fa-ellipsis-v" id="dropdown_menue_shoe_<%= @recommended_shoe.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu" aria-labelledby="dropdown_menue_shoe_<%= @recommended_shoe.id %>">
              <% if Wish.where(user: current_user, shoe: @recommended_shoe).present? %>
                <p class=" saved edit-user">You've already saved this!</p>
              <% else %>
                <%= link_to "Save to Wishlist", shoe_wishes_path(@recommended_shoe, outfit_id: @outfit.id), class: "edit-user", method: :post %>
              <% end %>
            </div>
          </div>
        </div>
       <% end %>
      <% end %>
    </div>
  </div>
  <div class="description_box">
    <p><i class="fas fa-history"></i> <%= @outfit.event_date.strftime("%d/%m/%y, %l:%M %p") %></p>
    <p><i class="<%= @outfit.event_type_icon %>"></i> <%= @outfit.event_type.humanize %></p>
    <p><i class="<%= @outfit.walking_time_icon %>"></i> <%= @outfit.walking_time.humanize %></p>
  </div>
</div>

<!-- Link to vote on the index page -->
<div class="container d-flex justify-content-center pt-3">
  <%= link_to "Time to Vote!", outfits_path, class:"blue-btn special" %>
</div>
<!-- Modal to edit outfit -->
<div class="modal fade showlinks" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title small-title-header">Edit outfit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= render "outfits/edit_form", outfit: @outfit %>
      </div>
    </div>
  </div>
</div>

<!-- Modal to Upload Shoes -->
<div class="modal fade showlinks" id="newshoeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title small-title-header">Upload Shoes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= render "shoes/form", outfit: @shoe %>
      </div>
    </div>
  </div>
</div>

app/views/outfits/trending.html.erb
<div class="container pbbig">
  <div class="outfit_header">
    <h2 class="h-trending">Top Trending Outfits!</h2>
    <p class="p-trending">This weeks most voted on shoes...</p>
  </div>
  <%# card to display outfit pic %>
  
  <% @trending_shoes.each do |trending_shoe| %>
    <div class="trending_outfit_container">
      <div class="trending-outfit-photo outfit-photo" style="background-image: url('<%= trending_shoe.outfit.photo.attached? ? cl_image_path(trending_shoe.outfit.photo.key) : 'photo.png' %>');">
      </div>
      <div class="trending-right-box">
        <div class="trending-top-bar top-bar mb-2">
          <%= image_tag trending_shoe.outfit.user.avatar.attached? ? trending_shoe.outfit.user.avatar : "photo.png", alt: "alttext", class: 'trending-avatar mr-3' %>
          <div class="user-info">
            <h5><%= link_to "@#{trending_shoe.outfit.user.username}", user_path(trending_shoe.outfit.user) %></h5>
            <p><%= trending_shoe.outfit.user.outfits.length %> outfits completed</p>
            <p><i class="<%= trending_shoe.outfit.event_type_icon %>"></i> <%= trending_shoe.outfit.event_type.humanize %></p>
            <p><i class="fas fa-walking"></i> <%= trending_shoe.outfit.walking_time.humanize %></p>
          </div>
        </div>
        <%= trending_shoe.photo.attached? ? cl_image_tag(trending_shoe.photo.key) : image_tag('photo.png') %>
      </div>
    </div>
  <% end %>
</div>