config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :outfits do
    resources :shoes, only: [:new, :create, :edit, :update]
    resources :feedbacks, only: [:create, :update]
  end

  resources :shoes, only: [:destroy] do
    # like method in shoes controller
    member do
      put "like" => "shoes#like"
    end
    resources :wishes, only: :create
  end

  resources :feedbacks, only: [:destroy]
  resources :users, only: [:show]

  get "trending", to: "outfits#trending"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, length: { minimum: 2, maximum: 10 }
  has_many :outfits
  has_many :feedbacks
  has_many :wishes
  has_one_attached :avatar

  acts_as_voter
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #no methods for user => function supported by devise
  #we will not edit/update/destroy users

  def show
    @new_outfit = Outfit.new
    @shoe = Shoe.new
    @user = User.find(params[:id])
  end
end

app/views/users/show.html.erb
<div class='user-show-page'>
  <div class="top-bar mt-2 mb-3">
    <%= image_tag @user.avatar.attached? ? @user.avatar : "photo.png", alt: "alttext", class: 'avatar mr-3' %>
    <div class="user-info">
      <h5>@<%= @user.username %></h5>
      <p><%= @user.outfits.length %> outfits completed</p>
    </div>
  </div>
  <% if current_page?(user_path(current_user)) %>
  <div class="fcen">
    <div class='blue-btn special' data-toggle="modal" data-target="#exampleModal">
      UPLOAD NEW OUTFIT
    </div>
  </div>
  <% end %>
  <div class="mb-3"></div>

  <div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <% if current_page?(user_path(current_user)) %>
      <li class="nav-item col-6">
      <% else %>
      <li class="nav-item col-12">
      <% end %>
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">
        <%= image_tag 'history.png' %>
        <div class="nav-link-border-hider"></div>
        </a>
      </li>
      <% if current_page?(user_path(current_user)) %>
      <li class="nav-item col-6">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">
        <%= image_tag 'heart.png' %>
        <div class="nav-link-border-hider"></div>
        </a>
        <!-- wishlist - only auto generated in next project phase - atm placeholder -->
      </li>
      <% end %>
    </ul>
  </div>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

      <div class='container pbbig mt-2'>
        <% @user.outfits.each do |outfit| %>
          <%= link_to outfit_path(outfit), class:'show-link' do %>
          <div class='outfit-user-card'>
            <div class="user-show-top-bar top-bar">
              <p><i class="fas fa-history"></i> <%= outfit.event_date.strftime("%d/%m/%y, %l:%M %p") || "has not been set" %></p>
              <p><i class="<%= outfit.event_type_icon %>"></i> <%= outfit.event_type.humanize %></p>
            </div>
            <div class=" user-outfit-photo outfit-photo" style="background-image: url('<%= outfit.photo.attached? ? cl_image_path(outfit.photo.key) : 'photo.png' %>');">
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% if current_page?(user_path(current_user)) %>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
    <%  current_user.wishes.each do |wish| %>
      <div class="shoe-div reco-shoe wish-shoe" style="background-image: url('<%= wish.shoe.photo.attached? ? cl_image_path(wish.shoe.photo.key) : "" %>')">
      <% if wish.shoe.url %>
        <a class="buy-now blue-btn" href="<%= wish.shoe.url %>">Buy Now</a>
      <% end %>
      </div>
    <% end %>
  </div>

  <% end %>
  </div>
</div>

<!-- modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title">New outfit</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= render "outfits/form", outfit: @new_outfit, user: current_user %>
      </div>
    </div>
  </div>
</div>