config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :outfits do
    resources :shoes, only: [:new, :create, :edit, :update]
    resources :feedbacks, only: [:create, :update]
  end

  resources :shoes, only: [:destroy] do
    # like method in shoes controller
    member do
      put "like" => "shoes#like"
    end
    resources :wishes, only: :create
  end

  resources :feedbacks, only: [:destroy]
  resources :users, only: [:show]

  get "trending", to: "outfits#trending"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="list-footer">
    <ul>
    <% if current_page?(root_path) %>
      <li class='current-path'>
        <%= link_to root_path do %>
          <%= image_tag 'home.png' %>
        <% end %>
    <% else %>
        <%= link_to root_path do %>
          <%= image_tag 'home.png', class:'other-path' %>
        <% end %>
    <% end %>
        </li>
      <% if current_page?(outfits_path) %>
        <li class='current-path'>
          <%= link_to outfits_path do %>
            <%= image_tag 'feed.png' %>
          <% end %>
      <% else %>
          <%= link_to outfits_path do %>
            <%= image_tag 'feed.png', class:'other-path' %>
          <% end %>
      <% end %>
        </li>
        <li>
      <% if user_signed_in? %>
        <div data-toggle="modal" data-target="#outfitModal">
          <%= image_tag 'plus.png', class:'other-path' %>
        </div>
      <% else user_signed_in? %>
        <div data-toggle="modal" data-target="#outfitModal">
          <%= image_tag 'plus.png', class:'current-path' %>
        </div>
      <% end %>
        </li>
      <% if current_page?(trending_path) %>
        <li class='current-path'>
          <%= link_to trending_path do %>
            <%= image_tag 'flame.png' %>
          <% end %>
      <% else %>
          <%= link_to trending_path do %>
            <%= image_tag 'flame.png', class:'other-path' %>
          <% end %>
      <% end %>
          </li>
      <% if user_signed_in? && !current_page?(user_path(current_user)) %>
        <li>
            <%= link_to user_path(current_user) do %>
              <%= image_tag current_user.avatar.attached? ? current_user.avatar : "user.png", class: "avatar-footer dropdown-toggle", id: "navbarDropdown" %>
            <% end %>
      <% elsif user_signed_in? && current_page?(user_path(current_user)) %>
        <%= link_to user_path(current_user) do %>
              <%= image_tag current_user.avatar.attached? ? current_user.avatar : "user.png", class: "avatar-current-path dropdown-toggle", id: "navbarDropdown" %>
            <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link login-footer border border-dark" %>
        </li>
      <% end %>
    </ul>
  </div>
</footer>


<!-- modal -->
<% if user_signed_in? && @new_outfit %>
<div class="modal fade" id="outfitModal" tabindex="-1" role="dialog" aria-labelledby="outfitModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title small-title-header">New outfit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <%= render "outfits/form", outfit: @new_outfit, user: current_user %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar1">
  <div>
    <h5 class='nav-font'>Shoes-Me</h5>
  </div>
  <div>
    <% if user_signed_in? #&& current_page?(user_path(current_user)) %>
      <div class="user-setting btn-group dropleft dropdown-options mr-3">
        <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag 'menu.png' %>
        </a>
        <div class="dropdown-menu">
          <%= link_to "Edit profile", edit_user_registration_path, class: 'edit-user mb-2' %>
          <%= link_to "Log out", destroy_user_session_path, class:'logout mb-2', method: :delete %>
          <%= link_to "About Us", about_path, class: 'logout' %>
        </div>
      </div>
    <% else %>
    <% end %>
  </div>
</div>

app/views/shared/_shoe_partial.html.erb
<!-- # this could potentially develop into card to use in wishlist
# as an alternative to modal - placeholder atm -->
<div class="Shoe-Card">
  <div class="Shoe-Card-Info">
    <div class="Shoe-Card-Photo" style="background-image:  ">
      <div class="Shoe-Card-Rating"></div>
     <!--  #where is this looking for instance variable @shoe to? which controller? -->
     <!-- # should be set up under shoes view - awaiting -->
      <%= shoe.brand %>
      <!-- # possible to link to external web => scraping -->
     <!--  <%#= link_to , "Buy Me",  %> -->
      <!-- # possible to incorporate price below from scraping? -->
      <div src="" class="Shoe-Card-Splash"></div>
    </div>
  </div>
</div>